"""Build v1.2 FP vectors: embed each model's structured capability summary
(local_descriptors/mix-instruct-v12-summaries.json -- strengths/performance/
flaws/traits, hand-written from reading real probe responses, see PROGRESS.md)
via the same frozen sentence-transformers/all-MiniLM-L6-v2 backbone used
elsewhere in this project (QueryEncoder), so the resulting vectors are
directly comparable via cosine similarity to the other FP descriptors.

This is a prototype: the summaries were authored by reading real MixInstruct
responses, not generated by an automated "lightweight backbone" call as the
v1.2 design intends (FP_IDEAS.md). See colab/test_v12_backbones.py for the
follow-up test of actual candidate backbone models + instruction variants.
"""
import argparse
import json
from pathlib import Path

import numpy as np
from sentence_transformers import SentenceTransformer

SUMMARIES_PATH = "local_descriptors/mix-instruct-v12-summaries.json"


def canonical_text(d: dict) -> str:
    return (f"Strengths: {d['strengths']} Performance: {d['performance']} "
            f"Flaws: {d['flaws']} Traits: {d['traits']}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pool", default="experts/pool-mix-instruct-7.json")
    ap.add_argument("--summaries", default=SUMMARIES_PATH)
    ap.add_argument("--out_dir", default="local_descriptors/mix-instruct-v12")
    ap.add_argument("--model_name", default="sentence-transformers/all-MiniLM-L6-v2")
    args = ap.parse_args()

    pool = json.load(open(args.pool))
    summaries = json.load(open(args.summaries))
    missing = [m for m in pool if m not in summaries]
    if missing:
        raise ValueError(f"No v1.2 summary written yet for: {missing}")

    model = SentenceTransformer(args.model_name)
    texts = [canonical_text(summaries[m]) for m in pool]
    emb = model.encode(texts, normalize_embeddings=True)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    for m, vec in zip(pool, emb):
        np.save(out_dir / f"{m}.npy", vec.astype(np.float32))
        print(f"  {m:55s} shape={vec.shape}")
    print(f"\nSaved {len(pool)} v1.2 vectors (dim={emb.shape[1]}) to {out_dir}")


if __name__ == "__main__":
    main()
